### ISSUE TITLE
no commands work on OS X 10.10.5, lldb-340.4.119

### ISSUE THREAD

**Issue by Fishrock123** [indutny/llnode#25]
see also https://github.com/indutny/llnode/issues/24

`bt`, `nodeinfo`, `source`, etc don't work for me.

I did both the simple and hard installs, no difference.

**Comment by indutny** [comment]
That's unfortunate consequence of dependency management in `brew`. Current version works with `lldb-360.1.50`, and this dependency is hard-coded in it. (There may be a way to fix it in homebrew, but I'm not aware of it).

May I ask you to build from source, and use:

```
svn co http://llvm.org/svn/llvm-project/lldb/tags/RELEASE_34/final/ lldb
```

As a `lldb` source?

**Comment by indutny** [comment]
I believe it is just a version mismatch. Closing the issue until some feedback.
