### ISSUE TITLE
v8 inspect and strings

### ISSUE THREAD

**Issue by thlorenz** [indutny/llnode#7]
It makes sense to cut off strings when executing `v8 inspect <string address>` since most strings are very long, but I'd like to be able to override this via an option.
In some cases (like when looking at a path var, i.e. `fs.read`) it's crucial to see the whole string.

Right now I get:
```
(lldb) v8 i 0x00002f51fd0bf901
0x00002f51fd0bf901:<String: "/Users/thlorenz/...">
```

But I'd like that to be:
```
(lldb) v8 i 0x00002f51fd0bf901
0x00002f51fd0bf901:<String: "/Users/thlorenz/dev/talks/debugging-profiling-nodejs/demos/demo-3/fs-read.js">
```

Not sure if this could be a setting that one would change globally that would affect every `inspect` or if should be another inspect, i.e. `deepinspect`.

**Comment by indutny** [comment]
Maybe `v8 i -R 0x...`? `-R` stands for raw here.

**Comment by indutny** [comment]
Fixed in, thank you!

**Comment by thlorenz** [comment]
Awesome!
